### PR TITLE
Tests.

### PR DESCRIPTION
**Pull request by DarryQueen**
Finally, code coverage back up to 90%. Lots of nuisances.

Note: should focus on writing RSpec tests instead of Cucumber. Cucumber only tests what an end-user can do via the browser. Some shady REST calls can still be made that won't be caught with Cucumber.

Reviewer: @nalnaji @delicioustoast

### CODE REVIEW

**Comment by delicioustoast** [comment]
One rspec test seems to be failing for me starting from the second try:

Failures:

  1) User accessing translations and related videos should dynamically update translated and untranslated videos
     Failure/Error: expect(@user.untranslated_videos).to include @video
       expected [] to include #<Video id: 1, youtube_id: "FavUpD_IjVY", title: "Factory-Created Video", description: "Factory-created description.", created_at: "2015-04-08 20:31:06", updated_at: "2015-04-08 20:31:06", starred: false, duration: nil>
       Diff:
       @@ -1,2 +1,2 @@
       -[#<Video id: 1, youtube_id: "FavUpD_IjVY", title: "Factory-Created Video", description: "Factory-created description.", created_at: "2015-04-08 20:31:06", updated_at: "2015-04-08 20:31:06", starred: false, duration: nil>]
       +[]
     # ./spec/models/user_spec.rb:85:in `block (3 levels) in <top (required)>'


And I'm consistently failing these scenarios on cucumber:
cucumber features/import_videos.feature:28 # Scenario: Import a CSV file properly.
    (And I should see "Charlie bit my finger - again !")
cucumber features/video_search_volunteer.feature:25 # Scenario: See suggested tags.
   (Then I should see "jessica" )
cucumber features/video_translation.feature:14 # Scenario: Assign video and unassign video.
  (Then I should see "Unassign Me" )


Travis seems to be working, so I don't know if it's just me. I tried testing both through the command line and through a new local repo via the GitHub app.

**Comment by DarryQueen** [comment]
This is because the test uploads an SRT file and doesn't remove it. The translation model checks to see if that file exists in order to mark it as complete. To get around this error, delete the file `public/srt/1/1.srt`.

Probably a shitty way to approach this, but I'm too lazy to fix it, and it works for now.

**Comment by delicioustoast** [comment]
Got it. Now all the rspec tests pass, but two cucumber scenarios consistently fail (The import CSV file and see suggested tags).

**Comment by nalnaji** [comment]
LGTM.

**Pull request merged**
