### PR TITLE
Flash cleanup.

### PR DESCRIPTION
**Pull request by DarryQueen**
Supports adding multiple flash messages by storing them in an array and rendering them dynamically.

Reviewer: @nalnaji

### CODE REVIEW

**Comment by nalnaji** [comment]
Good. Thanks for refactoring this.

**Comment by nalnaji** [comment]
Squash

**Comment by DarryQueen** [comment]
Should keep these two commits separate to distinguish between writing the method and using them.

**Comment by nalnaji** [comment]
Okay, that's chill. LGTM.

**Pull request merged**
