### PR TITLE
90% Coverage.

### PR DESCRIPTION
**Pull request by DarryQueen**
Finally...

Various tests.

Reviewer: @nalnaji

### CODE REVIEW

**Comment by nalnaji** [comment]
I get this error: 

screen shot 2015-03-06 at 2 01 01 am

**Comment by nalnaji** [comment]
That error only happens when we run "rake cucumber". It passes with "cucumber features". I will open an issue.

**Comment by DarryQueen** [comment]
For now, we should merge. Feature is bug-free; only tests are inconsistent.

**Comment by nalnaji** [comment]
Alright. Solid plan. LGTM.

**Comment by delicioustoast** [comment]
Maybe new step definitions for cucumber tests shouldn't be in web_steps.rb to prevent clutter. Like how we used movie_steps.rb in the step_definitions folder for our rottenpotatoes homework?

**Comment by DarryQueen** [comment]
Agreed. I put them there for consistency's sake. Edward, can you find all the changes we made to `web_steps.rb` and export them to a separate steps file?

**Pull request merged**
