### PR TITLE
Added social media login buttons.

### PR DESCRIPTION
**Pull request by DarryQueen**
Added pretty little Bootstrap buttons for social media login.

Reviewer: @nalnaji

### CODE REVIEW

**Comment by nalnaji** [comment]
To those interested in what it looks like but are too lazy to pull and run: 
screen shot 2015-03-04 at 9 05 58 am

I like it a lot, but before we merge this, let's get feedback from other group members.

**Comment by DarryQueen** [comment]
TODO (Darren): Fix the spacing between those two buttons. That whitespace is looking fat.

**Comment by DarryQueen** [comment]
Fixed.

**Comment by nalnaji** [comment]
I like it. Looks cool, good work. LGTM.

**Pull request merged**
