### PR TITLE
delete users feature

### PR DESCRIPTION
**Pull request by delicioustoast**
Can delete users (including oneself) as an admin/superadmin.

Not sure how translations will be affected once its user is deleted (can't test that locally for whatever reason).

Reviewers: @DarryQueen @nalnaji

### CODE REVIEW

**Comment by DarryQueen** [comment]
Going to make some edits.

**Comment by DarryQueen** [comment]
Made edits. Please re-review.

**Comment by delicioustoast** [comment]
LGTM

**Comment by DarryQueen** [comment]
Go ahead and merge.

**Pull request merged**
