### PR TITLE
Added searchable tags to videos.

### PR DESCRIPTION
**Pull request by DarryQueen**
Videos now include a searchable tags attribute, completely AJAX. Tags are analogous to arrays of strings.

Includes two new gems: [ActsAsTaggableOn](https://github.com/mbleigh/acts-as-taggable-on) and [Rails3 jQuery Autocomplete](https://github.com/crowdint/rails3-jquery-autocomplete).
Also includes installation for jQuery UI and custom jQuery UI stylesheet to match Bootstrap (though vanilla Bootstrap isn't perfect).

Minor yet nontrivial fixes for some fancy AJAX script.

Reviewer: @nalnaji @jonathanshum

### CODE REVIEW

**Comment by nalnaji** [comment]
It's fine, but I don't like how it says:

screen shot 2015-03-15 at 4 20 11 pm

**Comment by DarryQueen** [comment]
Okay, fixed it. Try now.

**Comment by nalnaji** [comment]
This

screen shot 2015-03-15 at 11 47 15 pm

Should look like this:
screen shot 2015-03-15 at 11 47 24 pm

**Comment by nalnaji** [comment]
LGTM, sick stuff Darren.

**Pull request merged**
